## Basic Configuration

baseurl = "https://chuquangtu.com"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Tu Chu Quang"
title = "Hey there! Have a nice day"

theme = "goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "UA-66148185-1"
enableRobotsTXT = true

## Site Settings
[params]
author = "Tu, Chu Quang"
intro = "Your geeky friend from Vietnam"
description = "I am a mind-reading full-stack web developer, a lifelong learner, a giver and an amateur comic artist. I have a great passion for web development and strong belief in the value of the combination of working hard and working smart. I believe that if we work hard in a smart-right-way, we could achieve more and better."
authorimage = "avatar.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "developer,web,fullstack,php,laravel,devops,reactjs,angularjs,minimalist,blog,hugo"

## Social Accounts
[params.social]
github = "tucq88"
linkedin = "tuchuquang"
twitter = "tucq88"
## email = "tucq88@gmail.com"

## Extras
[params.extra]
copyright = "© 2017. Tu Chu Quang"
poweredby = true
hightlightjs = false
bootstrapjs = false

## Main Menu
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 200
    url = "https://medium.com/@tucq88"